### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by srinivasb72s1** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#2]
hi sir,
I have impressed your work. Its really excellent work.
I have tried this code in google colab. It gave an error shown below.
Thank you sir.

File "<ipython-input-9-bd3c51839346>", line 16
    assert H%16 && W%16 && D%16, "All the input dimensions must be divisible by 16"
                 ^
SyntaxError: invalid syntax

**Comment by IAmSuyogJadhav** [comment]
Hi @srinivasb72s1 , Kindly use the implementation from [`model.py`](../blob/master/model.py) for using the model. Download the file to Google Colab using `wget` and follow the instructions in the `README`. The implementation contained in the notebook was old and inaccurate. I have deleted the old implementation (b3473ebe2d37bc0deb61809a3ff66768aa6a75da) in order to avoid any confusion .
